-- DO NOT EDIT THIS UNLESS YOU HAVE PERMISSION

--[[
stat format: (if a variable don't exist for that stat in the beequip, don't add it)
	["<beequip name>"] = {
		level = <level>,
		color = '<color>',
		limit = <limit>,
		desc = '<desc>',
		beesmas = <true if is from beesmas, false if not>,
		require = {
			beeReq = { //bee requirements, list by name (without 'Bee')
				'Bee 1',
				'Bee 2',
				...
			}
			otherReq = { //other non-bee requirements, list by line
				'Req 1',
				'Req 2',
				...
			}
		},
		stats = {
			{
				type = '<Keyword: Stat or Ability or Hive>',
				name = '<name of stat>',
				sign = '<sign of stat, % or +, Ability is always +>'
				baseMin = <minimum base value>,
				baseMax = <maximum base value>,
				maxValue = <maximum total value>,
				minBaseChance = <minimum chance of base stat appearing>,
				maxBaseChance = <maximum chance of base stat appearing>,
				minWeight = <minimum weight, if not a range then equal to below>,
				maxWeight = <maximum weight, if not a range then equal to above>,
				maxUpgrades = <maximum number of upgrades>,
				upgradeValue1 = <possible upgrade value 1>,
				bias = <bias to upgrade value 1 or 1>,
				upgradeValue2 = <possible upgrade value 2,
				caustic = <true if yes, false if no>,
			},
			{
				
			},
			...
		}
	}
]]--

return {
	["Bubble Light"] = {
		level = 8,
		color = 'Any',
		limit = 3,
		desc = 'The incandescent light bulb in this ornament brings methylene chloride to a magical boil.',
		beesmas = true,
		require = {
			otherReq = {
				'Bee must have Energy Mutation',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 30,
				baseMax = 50,
				maxValue = 170,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 6,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Movespeed',
				sign = '+',
				baseMin = 3,
				baseMax = 5,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bubble Pollen',
				sign = '%',
				baseMin = 15,
				baseMax = 30,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Mark Duration',
				sign = '%',
				baseMin = 5,
				baseMax = 15,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bubble Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 11,
				minBaseChance = 1,
				maxBaseChance = 10,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Movespeed',
				sign = '%',
				maxValue = 5,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Thumbtack"] = {
		level = 6,
		color = 'Red',
		limit = 2,
		desc = 'A small pin used to fasten stuff down or as a makeshift stinger.',
		beesmas = false,
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 1,
				baseMax = 3,
				maxValue = 33,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 20,
				maxUpgrades = 15,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 40,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 40,
				maxWeight = 40,
				maxUpgrades = 15,
				upgradeValue1 = 1,
				bias = 5,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 35,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 40,
				maxWeight = 40,
				maxUpgrades = 15,
				upgradeValue1 = 1,
				bias = 5,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '+',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 0.2,
				maxBaseChance = 10,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Attack',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 6,
				minBaseChance = 1,
				maxBaseChance = 10,
				minWeight = 0.04,
				maxWeight = 1,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Attack',
				sign = '%',
				maxValue = 3,
				minWeight = 0.04,
				maxWeight = 1,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Reindeer Antlers"] = {
		level = 8,
		color = 'Any',
		limit = 1,
		desc = 'These magic antlers and glowing-red nose help Puppy Bee guide you through darkness!',
		beesmas = true,
		require = {
			beeReq = {
				'Puppy',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Focus',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Reindeer Fetch',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Baby Love',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = .0167,
				maxWeight = .05,
				maxUpgrades = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '%',
				maxValue = 20,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bond From Treats',
				sign = '%',
				maxValue = 3,
				minWeight = .01,
				maxWeight = .05,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Warm Scarf"] = {
		level = 5,
		color = 'Any',
		limit = 3,
		desc = 'This winter scarf keeps bees warm in the field.',
		beesmas = true,
		require = {
			beeReq = {
				'Basic',
				'Rad',
				'Exhausted',
				'Frosty',
				"Shy",
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 25,
				baseMax = 35,
				maxValue = 75,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = 25,
				baseMax = 35,
				maxValue = 75,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Field Capacity',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Field Capacity',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '%',
				maxValue = 10,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Toy Drum"] ={
		level = 7,
		color = 'Any',
		limit = 2,
		desc = 'A small percussion instrument that keeps you in step.',
		beesmas = true,
		require = {
			beeReq = {
				'Brave',
				'Demo',
				'Bucko',
				'Riley',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '%',
				baseMin = 1,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 75,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -20,
				baseMax = -10,
				maxValue = -10,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 5,
				maxBaseChance = 90,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Haste',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Pollen',
				sign = '%',
				maxValue = 10,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
		},
	},
	["Smiley Sticker"] = {
		level = 7,
		color = 'Any',
		limit = 2,
		desc = 'This happy seal of approval is only for the brightest of bees.',
		beesmas = false,
		require = {
			otherReq = {
				'Bee must be Gifted',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = 15,
				baseMax = 25,
				maxValue = 85,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bomb Pollen',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Mark Duration',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 30,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Honey Mark',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = .02,
				maxWeight = 0.2,
				caustic = true,
			},
			{
				type = 'Ability',
				name = 'Blue Bomb',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = .02,
				maxWeight = 0.2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Mark Duration',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 2.5,
				maxBaseChance = 10,
				minWeight = .1,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Max Bee Energy',
				sign = '%',
				maxValue = 3,
				minWeight = 1,
				maxWeight = 5,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Bang Snap"] = {
		level = 10,
		color = 'Any',
		limit = 1,
		desc = 'These are the only explosives suitable for young bees and beekeepers.',
		beesmas = false,
		require = {
			otherReq = {
				'Bees must be Common, Rare, or Epic.'
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bomb Pollen',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 23,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Bomb',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Bomb+',
				linkOverride = 'Bomb',
				sign = '+',
				minWeight = 0.1,
				maxWeight = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Bomb Pollen',
				sign = '%',
				maxValue = 10,
				minWeight = .5,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bomb Instant Conversion',
				sign = '%',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 5,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Buzz Bomb Instant Conversion',
				sign = '%',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Red Bomb Instant Conversion',
				sign = '%',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Blue Bomb Instant Conversion',
				sign = '%',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Sweatband"] = {
		level = 5,
		color = 'Any',
		limit = 3,
		desc = 'This absorbant strap keeps sweat out of your eyes while looking vaguely patriotic.',
		beesmas = false,
		stats = {
			{
				type = 'Stat',
				name = 'Bee Energy',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 80,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'White Gather Amount',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 40,
				maxBaseChance = 60,
				minWeight = 15,
				maxWeight = 15,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Red Gather Amount',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 40,
				maxBaseChance = 60,
				minWeight = 15,
				maxWeight = 15,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Blue Gather Amount',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 40,
				maxBaseChance = 60,
				minWeight = 15,
				maxWeight = 15,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 5,
				maxBaseChance = 25,
				minWeight = 0.01,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 5,
				maxBaseChance = 25,
				minWeight = 0.02,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 5,
				maxBaseChance = 25,
				minWeight = 0.01,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Max Bee Energy',
				sign = '%',
				maxValue = 5,
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 0.01,
				maxWeight = 2,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pollen',
				sign = '%',
				maxValue = 1,
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 0.01,
				maxWeight = 0.1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			}
		},
	},
	["Pinecone"] = {
		level = 9,
		color = 'Any',
		limit = 2,
		desc = 'A seed-producing organ produced by Conifer trees.',
		beesmas = true,
		require = {
			beeReq = {
				'Bumble',
				'Stubborn',
				'Bucko',
				'Frosty',
				'Carpenter',
				'Bear',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 70,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pine Tree Forest Capacity',
				sign = '%',
				baseMin = 8,
				baseMax = 15,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pine Tree Forest Pollen',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 3,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Bottle Cap"] = {
		level = 4,
		color = 'Any',
		limit = 2,
		desc = 'The discarded top from a bottle of pop.',
		require = {
			otherReq = {
				'Bee must be Common or Rare',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 10,
				baseMax = 20,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 15,
				upgradeValue1 = 3,
				bias = 2,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 60,
				minBaseChance = 1,
				maxBaseChance = 1,
				minWeight = 30,
				maxWeight = 30,
				maxUpgrades = 10,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 12,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				bias = 10,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Buzz Bomb',
				sign = '+',
				minWeight = 0.1,
				maxWeight = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Critical Power',
				sign = '%',
				maxValue = 15,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 5,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 3,
				caustic = false,
			},
		},
	},
	["Paper Angel"] = {
		level = 8,
		color = 'Any',
		limit = 2,
		desc = 'Designs for this folded paper doll came to you in a dream.',
		beesmas = true,
		require = {
			beeReq = {
				'Bomber',
				'Rascal',
				'Shy',
				'Photon',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'White Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 23,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 0,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Token Link',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Pollen',
				sign = '%',
				maxValue = 3,
				minWeight = 0.5,
				maxWeight = 5,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Token Lifespan',
				sign = '%',
				maxValue = 5,
				minWeight = 1,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			}
		},
	},
	["Whistle"] = {
		level = 8,
		color = 'Any',
		limit = 1,
		desc = 'Bees can blow into this to startle everyone around them.',
		beesmas = false,
		require = {
			beeReq = {
				'Brave',
				'Commander',
				'Rascal',
				'Demo',
				'Cool',
				'Rage',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Movespeed',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 40,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 15,
				upgradeValue1 = 1,
				bias = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 15,
				baseMax = 25,
				maxValue = 85,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 67,
				maxWeight = 67,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -55,
				baseMax = -45,
				maxValue = -45,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Haste',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Melody',
				sign = '+',
				minWeight = 0.01,
				maxWeight = 0.1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Bee Movespeed',
				sign = '%',
				maxValue = 1,
				minWeight = 0.2,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 20,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 1,
				upgradeValue2 = 2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Player Movespeed',
				sign = 'x',
				maxValue = 1.01,
				minWeight = 0.1,
				maxWeight = 0.4,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Electric Candle"] = {
		level = 6,
		color = 'Red',
		limit = 3,
		desc = 'A battery powered candle that produces an acceptible [sic] flicker.',
		beesmas = true,
		stats = {
			{
				type = 'Stat',
				name = 'Red Gather Amount',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Flame Pollen',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gathering Flames',
				sign = '%',
				baseMin = 1,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Flame Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 11,
				minBaseChance = 1,
				maxBaseChance = 5,
				minWeight = 1,
				maxWeight = 5,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Thimble"] = {
		level = 3,
		color = 'Any',
		limit = 3,
		desc = 'A tiny cup that usually protects our fingers. Bees can wear it as a hat.',
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 20,
				baseMax = 40,
				maxValue = 80,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 75,
				maxWeight = 75,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 1,
				baseMax = 5,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 10,
				minBaseChance = 0.1,
				maxBaseChance = 1,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 9,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert Rate',
				sign = 'x',
				maxValue = 1.01,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1.01,
				caustic = true,
			},
		},
	},
	["Festive Wreath"] = {
		level = 10,
		color = 'Red',
		limit = 1,
		desc = "This ornate wreath was specially made to suit Festive Bee's taste.",
		beesmas = true,
		require = {
			beeReq = {
				'Festive',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 5,
				baseMax = 15,
				maxValue = 55,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 15,
				baseMax = 30,
				maxValue = 110,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Red Bomb Pollen',
				sign = '%',
				baseMin = 20,
				baseMax = 40,
				maxValue = 40,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Mark Duration',
				sign = '%',
				baseMin = 2,
				baseMax = 8,
				maxValue = 13,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 10,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Festive Mark',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 5000,
				baseMax = 15000,
				maxValue = 110000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 20,
				upgradeValue1 = 500,
				bias = 2,
				upgradeValue2 = 5000,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Ticket Chance',
				sign = '%',
				maxValue = 5,
				minWeight = 0.01,
				maxWeight = 0.05,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Bee Convert Rate',
				sign = '%',
				maxValue = 10,
				minWeight = 4,
				maxWeight = 15,
				maxUpgrades = 5,
				upgradeValue1 = 2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Honey At Hive',
				sign = '%',
				maxValue = 10,
				minWeight = 8,
				maxWeight = 30,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Snow Tiara"] = {
		level = 12,
		color = 'Any',
		limit = 1,
		desc = 'A beautiful crown perfect for occasions where you build snowbears with your sister.',
		beesmas = true,
		require = {
			beeReq = {
				'Cool',
				'Stubborn',
				'Shocked',
				'Frosty',
				'Diamond',
				'Windy',
			},
			otherReq = {
				'Bee must be Gifted',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 25,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 30,
				maxWeight = 60,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert At Hive',
				sign = '%',
				baseMin = 10,
				baseMax = 25,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Blue Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 25,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'White Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 25,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Field Capacity',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Field Capacity',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey From Tokens',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 5,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			}
		},
	},
	["Paperclip"] = {
		level = 7,
		color = 'Any',
		limit = 2,
		desc = 'A helpful trinket that keeps stacks of paper together without staples, tape, or glue.',
		require = {
			otherReq = {
				'Bee must be Rare or Epic',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 6,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 5,
				baseMax = 15,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Rate At Hive',
				sign = '%',
				maxValue = 30,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Token Link',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 0.067,
				maxWeight = 0.67,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Token Lifespan',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 9,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 0.2,
				maxWeight = 1,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Pollen',
				sign = '%',
				maxValue = 3,
				minWeight = 0.4,
				maxWeight = 2,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			}
		},
	},
	["Lei"] = {
		level = 14,
		color = 'Any',
		limit = 1,
		desc = 'Threaded petals to drape around your décolletage.',
		require = {
			beeReq = {
				'Basic',
				'Looker',
				'Stubborn',
				'Hasty',
				'Exhausted',
			}
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gather Pollination',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 50,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Red Boost or Blue Boost',
				linkOverride = 'Boost',
				sign = '+',
				minWeight = 0.1,
				maxWeight = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Sunflower Field Pollen',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Flower Field Pollen',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Rose Field Pollen',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Coconut Field Pollen',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 5,
				maxBaseChance = 10,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
		},
	},
	["Elf Cap"] = {
		level = 3,
		color = 'Any',
		limit = 2,
		desc = 'A darling cap fitted with a bell to keep the laborer alert.',
		beesmas = true,
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 25,
				baseMax = 50,
				maxValue = 110,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Rate At Hive',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert Rate At Hive',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 20,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey At Hive',
				sign = '%',
				maxValue = 20,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
		},
	},
	["Lump Of Coal"] = {
		level = 13,
		color = 'Any',
		limit = 3,
		desc = 'Naughty bees are forced to carry this burdensome load.',
		beesmas = true,
		stats = {
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -80,
				baseMax = -70,
				maxValue = -70,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Movespeed',
				sign = '%',
				baseMin = -50,
				baseMax = -40,
				maxValue = -40,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bomb Pollen',
				sign = '%',
				maxValue = 40,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bomb Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Buzz Bomb Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 15,
				maxBaseChance = 15,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Bomb Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 15,
				maxBaseChance = 15,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Bomb Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 13,
				minBaseChance = 15,
				maxBaseChance = 15,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 5,
				maxBaseChance = 5,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 2,
				minBaseChance = 10,
				maxBaseChance = 10,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 2,
				minBaseChance = 10,
				maxBaseChance = 10,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 2,
				minBaseChance = 10,
				maxBaseChance = 10,
				caustic = false,
			},
		},
	},
	["Single Mitten"] = {
		level = 6,
		color = 'Any',
		limit = 3,
		desc = 'This winter-themed mitten is missing its partner.',
		beesmas = true,
		require = {
			otherReq = {
				'Bee must be Rare, Epic, or Legendary',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 5,
				baseMax = 10,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 5,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bomb Pollen',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 75,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 5,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 7500,
				baseMax = 10000,
				maxValue = 15000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 25,
				maxWeight = 100,
				maxUpgrades = 10,
				upgradeValue1 = 100,
				bias = 3,
				upgradeValue2 = 500,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Pollen',
				sign = '%',
				maxValue = 9,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 3,
				caustic = false,
			},
		},
	},
	["Bandage"] = {
		level = 3,
		color = 'Any',
		limit = 3,
		desc = 'Heals cuts in no time and make a bee look tough.',
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 3,
				baseMax = 6,
				maxValue = 16,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 3,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '+',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Bee Attack',
				sign = 'x',
				maxValue = 1.01,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1.01,
				caustic = true,
			},
		},
	},
	["Beesmas Top"] = {
		level = 4,
		color = 'Any',
		limit = 3,
		desc = 'Younger bees enjoy giving this traditional Beesmas toy a spin.',
		beesmas = true,
		require = {
			otherReq = {
				'Bee must be Common or Rare',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 30,
				maxWeight = 100,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -35,
				baseMax = -25,
				maxValue = 125,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 15,
				upgradeValue1 = 5,
				bias = 2,
				upgradeValue2 = 10,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 30,
				maxWeight = 100,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '+',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 10,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Critical Power',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Peppermint Antennas"] = {
		level = 7,
		color = 'Any',
		limit = 3,
		desc = 'These grant a soothing cooling sensation to the bee who wears them.',
		beesmas = true,
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 2,
				baseMax = 4,
				maxValue = 44,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '%',
				baseMin = 2,
				baseMax = 4,
				maxValue = 44,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 4,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 6,
				minBaseChance = 20,
				maxBaseChance = 60,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 6,
				minBaseChance = 20,
				maxBaseChance = 60,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Movespeed',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Rate',
				sign = '%',
				maxValue = 1,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Snowglobe"] = {
		level = 7,
		color = 'Any',
		limit = 2,
		desc = 'Keep a little ball of winter wonder with you all year long.',
		beesmas = true,
		require = {
			beeReq = {
				'Basic',
				'Bumble',
				'Cool',
				"Bucko",
				"Frosty",
				"Windy",
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bomb Pollen',
				sign = '%',
				baseMin = 30,
				baseMax = 50,
				maxValue = 90,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				maxValue = 1,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Snowglobe Shake',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bomb Pollen',
				sign = '%',
				maxValue = 5,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Charm Bracelet"] = {
		level = 12,
		color = 'Any',
		limit = 1,
		desc = 'Bedazzles your bees with a shimmering assortment of symbols that are lucky somehow.',
		beesmas = false,
		require = {
			otherReq = {
				'Bee must be Legendary',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 1,
				baseMax = 15,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Mark Duration',
				sign = '%',
				baseMin = 4,
				baseMax = 8,
				maxValue = 8,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 3,
				baseMax = 6,
				maxValue = 6,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Melody',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 0.1,
				maxWeight = 2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Loot Luck',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey At Hive',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 20,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey From Tokens',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 20,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert Rate At Hive',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 10,
				maxBaseChance = 20,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Mushroom Field Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 41,
				minBaseChance = 10,
				maxBaseChance = 20,
				minWeight = 25,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Flower Field Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 41,
				minBaseChance = 10,
				maxBaseChance = 20,
				minWeight = 25,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Sunflower Field Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 41,
				minBaseChance = 10,
				maxBaseChance = 20,
				minWeight = 25,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Dandelion Field Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 41,
				minBaseChance = 10,
				maxBaseChance = 20,
				minWeight = 25,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
		},
	},
	["Kazoo"] = {
		level = 9,
		color = 'Any',
		limit = 1,
		desc = "A plastic instrument that's kind of like a recorder, but more obnoxious.",
		require = {
			beeReq = {
				'Brave',
				'Bumble',
				'Bubble',
				'Riley',
				'Shocked',
				'Buoyant',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 90,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 90,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -55,
				baseMax = -45,
				maxValue = -45,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Melody',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Critical Power',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 10,
				minBaseChance = 5,
				maxBaseChance = 25,
				minWeight = 1,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 5,
				minWeight = 2,
				maxWeight = 8,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Icicles"] = {
		level = 10,
		color = 'Blue',
		limit = 2,
		desc = 'Incredibly cold and incredibly sharp.',
		beesmas = true,
		require = {
			otherReq = {
				'Bee must know "Blue Bomb" ability',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 45,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 5,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Blue Bomb Pollen',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 110,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Cactus Field Pollen',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Bomb Pollen',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Monster Respawn Time',
				sign = '%',
				maxValue = 5,
				minWeight = 0.1,
				maxWeight = 1,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Beesmas Tree Hat"] = {
		level = 10,
		color = 'Any',
		limit = 3,
		desc = "A party hat that's been painted to look like a Beesmas Tree.",
		beesmas = true,
		require = {
			otherReq = {
				'Bee must have a Mutation'
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 50,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 50,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 2,
				minBaseChance = 5,
				maxBaseChance = 50,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 10000,
				baseMax = 25000,
				maxValue = 35000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 250,
				bias = 2,
				upgradeValue2 = 1000,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert At Hive',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Toy Horn"] = {
		level = 9,
		color = 'Any',
		limit = 2,
		desc = 'The tiny brass instrument can be heard from miles away.',
		beesmas = true,
		require = {
			beeReq = {
				'Brave',
				'Rage',
				'Lion',
				'Cobalt',
				'Crimson',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 30,
				baseMax = 60,
				maxValue = 180,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 3,
				bias = 3,
				upgradeValue2 = 6,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 25,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -20,
				baseMax = -10,
				maxValue = -10,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 3,
				maxValue = 6,
				minBaseChance = 5,
				maxBaseChance = 90,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Melody',
				sign = '+',
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Pollen',
				sign = '%',
				maxValue = 5,
				minWeight = 2,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Convert Rate',
				sign = '%',
				maxValue = 20,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
		},
	},
	["Pink Shades"] = {
		level = 10,
		color = 'Any',
		limit = 1,
		desc = 'Flamboyant glasses that protect your eyes while making you look like a rock star.',
		require = {
			beeReq = {
				'Basic',
				'Rad',
				'Bomber',
				'Demo',
				'Honey',
				'Shy',
			},
			otherReq = {
				'Bee must be Gifted',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 15,
				baseMax = 25,
				maxValue = 65,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 15,
				maxWeight = 15,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 25,
				baseMax = 50,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 68,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 55,
				maxWeight = 55,
				maxUpgrades = 19,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Super-Crit Chance',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 55,
				minBaseChance = 25,
				maxBaseChance = 75,
				minWeight = 30,
				maxWeight = 30,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Focus',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 5,
				maxWeight = 25,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Chance',
				sign = '%',
				maxValue = 1,
				minWeight = 2.5,
				maxWeight = 10,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 30,
				minWeight = 2.5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
		},
	},
	["Bead Lizard"] = {
		level = 9,
		color = 'Any',
		limit = 1,
		desc = 'Threaded plastic beads arranged to look like a reptile. Would make a good keychain.',
		require = {
			otherReq = {
				'Bee must be Common or Rare',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 110,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Flame Chance',
				sign = '%',
				baseMin = 8,
				baseMax = 12,
				maxValue = 52,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bubble Chance',
				sign = '%',
				baseMin = 8,
				baseMax = 12,
				maxValue = 52,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Token Link',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 5,
				maxWeight = 33,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Bubble Pollen',
				sign = '%',
				maxValue = 10,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Flame Pollen',
				sign = '%',
				maxValue = 10,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Ability Pollen',
				sign = '%',
				maxValue = 5,
				minWeight = 0.1,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Camo Bandana"] = {
		level = 8,
		color = 'Any',
		limit = 3,
		desc = 'For any bee that wants to be seen looking like it wants to be unseen.',
		require = {
			otherReq = {
				'Bee must know "Bomb" ability',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Buzz Bomb Pollen',
				sign = '%',
				baseMin = 15,
				baseMax = 25,
				maxValue = 105,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '+',
				baseMin = 1,
				baseMax = 1,
				maxValue = 1,
				minBaseChance = 5,
				maxBaseChance = 50,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				maxValue = 80,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 300,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 10,
				bias = 2,
				upgradeValue2 = 15,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Buzz Bomb Pollen',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 33,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pumpkin Field Capacity',
				sign = '%',
				baseMin = 4,
				baseMax = 8,
				maxValue = 13,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Coconut Field Capacity',
				sign = '%',
				baseMin = 4,
				baseMax = 8,
				maxValue = 13,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 5,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Beret"] = {
		level = 11,
		color = 'Blue',
		limit = 2,
		desc = 'Only the blue bees are cool enough to don this comfy cap.',
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 50,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 5,
				maxValue = 5,
				minBaseChance = 10,
				maxBaseChance = 50,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Blue Boost',
				sign = '+',
				minBaseChance = 0,
				maxBaseChance = 0,
				minWeight = 0.02,
				maxWeight = 0.2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 10000,
				baseMax = 35000,
				maxValue = 50000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 25,
				maxWeight = 50,
				maxUpgrades = 5,
				upgradeValue1 = 2000,
				bias = 2,
				upgradeValue2 = 3000,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Field Capacity',
				sign = '%',
				maxValue = 5,
				minWeight = 2,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '%',
				maxValue = 5,
				minWeight = 0.1,
				maxWeight = 5,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Poinsettia"] = {
		level = 6,
		color = 'Any',
		limit = 2,
		desc = 'A gorgeous red flower so vibrant it is reserved for a special time of the year.',
		beesmas = true,
		require = {
			otherReq = {
				'Bee must know "Boost" ability',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Red Gather Amount',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Pollination Chance',
				sign = '%',
				baseMin = 10,
				baseMax = 20,
				maxValue = 40,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 25,
				maxWeight = 75,
				maxUpgrades = 20,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bee Gather Pollen',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 31,
				minBaseChance = 20,
				maxBaseChance = 50,
				minWeight = 10,
				maxWeight = 35,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Pollen',
				sign = '%',
				maxValue = 25,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 5,
				upgradeValue1 = 2,
				upgradeValue2 = 5,
				caustic = false,
			},
		},
	},
	["Autumn Sunhat"] = {
		level = 16,
		color = 'Any',
		limit = 1,
		desc = 'A lovely straw hat made from 100% fall-sourced materials.',
		require = {
			beeReq = {
				'Hasty',
				'Bumble',
				'Looker',
				'Exhausted',
				'Diamond',
				'Puppy',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 60,
				baseMax = 80,
				maxValue = 200,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 20,
				upgradeValue1 = 4,
				bias = 2,
				upgradeValue2 = 6,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 60,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 10,
				upgradeValue1 = 2,
				bias = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'White Gather Amount',
				sign = '%',
				baseMin = 40,
				baseMax = 60,
				maxValue = 110,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 10,
				upgradeValue1 = 3,
				bias = 2,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 8,
				baseMax = 15,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 40000,
				baseMax = 60000,
				maxValue = 100000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 33,
				maxUpgrades = 5,
				upgradeValue1 = 4000,
				bias = 2,
				upgradeValue2 = 8000,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Sunflower Field Pollen',
				sign = '%',
				baseMin = 18,
				baseMax = 24,
				maxValue = 44,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 33,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pumpkin Patch Pollen',
				sign = '%',
				baseMin = 18,
				baseMax = 24,
				maxValue = 44,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 20,
				maxWeight = 33,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 2,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Field Capacity',
				sign = '%',
				baseMin = 6,
				baseMax = 10,
				maxValue = 22,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 15,
				maxWeight = 25,
				maxUpgrades = 12,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'White Pollen',
				sign = '%',
				maxValue = 30,
				minWeight = 5,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 3,
				caustic = true,
			},
		},
	},
	["Camphor Lip Balm"] = {
		level = 12,
		color = 'Any',
		limit = 1,
		desc = 'Soothes chapped lips with a slight cooling sensation.',
		require = {
			beeReq = {
				'Cool',
				'Stubborn',
				"Commander",
				'Bubble',
				'Crimson',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '+',
				baseMin = 20,
				baseMax = 30,
				maxValue = 75,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 15,
				upgradeValue1 = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Power',
				sign = '%',
				baseMin = 50,
				baseMax = 70,
				maxValue = 145,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 15,
				upgradeValue1 = 3,
				bias = 3,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Pepper Patch Pollen',
				sign = 'x',
				baseMin = 1.03,
				baseMax = 1.05,
				maxValue = 1.08,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 2,
				maxWeight = 8,
				maxUpgrades = 3,
				upgradeValue1 = 1.01,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Bubble Pollen',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Gold Bubble Pollen',
				sign = '%',
				maxValue = 12,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 4,
				upgradeValue1 = 2,
				bias = 3,
				upgradeValue2 = 3,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Honey From Instant Conversion',
				sign = '%',
				maxValue = 10,
				minWeight = .01,
				maxWeight = 1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				caustic = true,
			},
		},
	},
	["Candy Ring"] = {
		level = 14,
		color = 'Any',
		limit = 1,
		desc = 'Keeps some sugar on hand to satisfy on demand.',
		require = {
			beeReq = {
				'Stubborn',
				'Bumble',
				'Honey',
				'Diamond',
				'Festive',
				'Gummy',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Energy',
				sign = '+',
				baseMin = 60,
				baseMax = 80,
				maxValue = 240,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 100,
				maxWeight = 100,
				maxUpgrades = 20,
				upgradeValue1 = 6,
				upgradeValue2 = 8,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 20,
				baseMax = 30,
				maxValue = 80,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 10,
				upgradeValue1 = 3,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 5,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 20,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Honey At Hive',
				sign = '%',
				baseMin = 2,
				baseMax = 5,
				maxValue = 25,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 1,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey Per Goo',
				sign = '%',
				baseMin = 1,
				baseMax = 1,
				maxValue = 7,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = .5,
				maxWeight = 5,
				maxUpgrades = 6,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey From Tokens',
				sign = 'x',
				maxValue = 1.01,
				minWeight = .005,
				maxWeight = .02,
				maxUpgrades = 1,
				upgradeValue1 = 1.01,
				caustic = true,
			},
		},
	},
	["Demon Talisman"] = {
		level = 13, 
		color = 'Red',
		limit = 1,
		desc = 'An ornament trying hard to look conventionally evil.',
		require = {
			beeReq = {
				'Demon',
			},
			otherReq = {
				'Bee must have a Mutation',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '%',
				baseMin = 50,
				baseMax = 70,
				maxValue = 95,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 33,
				maxWeight = 33,
				maxUpgrades = 5,
				upgradeValue1 = 3,
				bias = 2,
				upgradeValue2 = 5,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gather Amount',
				sign = '%',
				baseMin = 50,
				baseMax = 70,
				maxValue = 160,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 16,
				maxWeight = 16,
				maxUpgrades = 15,
				upgradeValue1 = 4,
				bias = 2,
				upgradeValue2 = 6,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Ability Pollen',
				sign = '%',
				baseMin = 50,
				baseMax = 70,
				maxValue = 160,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 16,
				maxWeight = 16,
				maxUpgrades = 15,
				upgradeValue1 = 4,
				bias = 2,
				upgradeValue2 = 6,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gathering Flames Chance',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 21,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 23,
				maxWeight = 23,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Super-Crit Chance',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 30,
				minBaseChance = 1,
				maxBaseChance = 5,
				minWeight = 10,
				maxWeight = 10,
				maxUpgrades = 10,
				upgradeValue1 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Movespeed',
				sign = '%',
				baseMin = -70,
				baseMax = -60,
				maxValue = -60,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Energy',
				sign = '%',
				baseMin = -30,
				baseMax = -20,
				maxValue = -20,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Ability',
				name = 'Inferno',
				sign = '+',
				minWeight = .0125,
				maxWeight = .1,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Red Bomb Pollen',
				sign = '%',
				baseMin = 7,
				baseMax = 13,
				maxValue = 35,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 40,
				maxWeight = 60,
				maxUpgrades = 11,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Flame Pollen',
				sign = '%',
				baseMin = 7,
				baseMax = 13,
				maxValue = 35,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 40,
				maxWeight = 60,
				maxUpgrades = 11,
				upgradeValue1 = 1,
				bias = 3,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Red Bomb Conversion',
				sign = '%',
				baseMin = 6,
				baseMax = 9,
				maxValue = 14,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Flame Conversion',
				sign = '%',
				baseMin = 6,
				baseMax = 9,
				maxValue = 14,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 25,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Demon Bee Conversion',
				sign = '%',
				baseMin = 10,
				baseMax = 10,
				maxValue = 10,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Super-Crit Power',
				sign = '%',
				maxValue = 10,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 5,
				upgradeValue1 = 2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Max Bee Energy',
				sign = '%',
				baseMin = -25,
				baseMax = -20,
				maxValue = -20,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Player Movespeed',
				sign = '+',
				baseMin = -5,
				baseMax = -5,
				maxValue = -5,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Blue Pollen',
				sign = 'x',
				baseMin = 0.5,
				baseMax = 0.5,
				maxValue = 0.5,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
		},
	},
	["Pink Eraser"] = {
		level = 12,
		color = 'Any',
		limit = 1,
		desc = 'Unmarks your marks.',
		require = {
			otherReq = {
				'Bee must have a Convert Amount mutation',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '+',
				baseMin = 20,
				baseMax = 40,
				maxValue = 100,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				upgradeValue2 = 3,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Instant Conversion',
				sign = '%',
				baseMin = 15,
				baseMax = 20,
				maxValue = 30,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Mark Duration',
				sign = '%',
				baseMin = -90,
				baseMax = -90,
				maxValue = -90,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Red Bomb Conversion',
				sign = '%',
				baseMin = 7,
				baseMax = 10,
				maxValue = 15,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Bee Gather Conversion',
				sign = '%',
				baseMin = 3,
				baseMax = 5,
				maxValue = 8,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 5,
				maxWeight = 20,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Honey From Instant Conversion',
				sign = '%',
				baseMin = 0.5,
				baseMax = 1,
				maxValue = 4,
				minBaseChance = 10,
				maxBaseChance = 50,
				minWeight = .02,
				maxWeight = .2,
				maxUpgrades = 6,
				upgradeValue1 = 0.5,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Unique Instant Conversion',
				sign = '%',
				maxValue = 5,
				minWeight = .02,
				maxWeight = .1,
				maxUpgrades = 1,
				upgradeValue1 = 1,
				upgradeValue2 = 5,
				caustic = true,
			},
		},
	},
	["Rose Headband"] = {
		level = 13,
		color = 'Any',
		limit = 1,
		desc = "Compliments a bee's rosy complexion and flower-esque fleeting youth.",
		require = {
			beeReq = {
				'Basic',
				'Rascal',
				'Riley',
				'Diamond',
				'Windy',
				'Vicious',
			},
		},
		stats = {
			{
				type = 'Stat',
				name = 'Bee Attack',
				sign = '+',
				baseMin = 2,
				baseMax = 4,
				maxValue = 7,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 15,
				maxWeight = 25,
				maxUpgrades = 3,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Convert Amount',
				sign = '%',
				baseMin = 40,
				baseMax = 60,
				maxValue = 140,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 50,
				maxWeight = 50,
				maxUpgrades = 20,
				upgradeValue1 = 2,
				upgradeValue2 = 4,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Gather Pollination Chance',
				sign = '%',
				baseMin = 10,
				baseMax = 15,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 15,
				maxWeight = 25,
				maxUpgrades = 5,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Critical Chance',
				sign = '%',
				baseMin = 5,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 10,
				maxBaseChance = 25,
				minWeight = 15,
				maxWeight = 25,
				maxUpgrades = 5,
				upgradeValue1 = 2,
				caustic = false,
			},
			{
				type = 'Stat',
				name = 'Bee Ability Rate',
				sign = '%',
				baseMin = 1,
				baseMax = 2,
				maxValue = 2,
				minBaseChance = 100,
				maxBaseChance = 100,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Capacity',
				sign = '+',
				baseMin = 20000,
				baseMax = 30000,
				maxValue = 55000,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 30,
				maxUpgrades = 5,
				upgradeValue1 = 2500,
				bias = 2,
				upgradeValue2 = 5000,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Rose Field Pollen',
				sign = '%',
				baseMin = 14,
				baseMax = 20,
				maxValue = 40,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 10,
				maxWeight = 30,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				bias = 10,
				upgradeValue2 = 2,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Red Field Capacity',
				sign = '%',
				baseMin = 6,
				baseMax = 10,
				maxValue = 20,
				minBaseChance = 100,
				maxBaseChance = 100,
				minWeight = 6,
				maxWeight = 30,
				maxUpgrades = 10,
				upgradeValue1 = 1,
				caustic = false,
			},
			{
				type = 'Hive',
				name = 'Instant Rose Field Conversion',
				sign = '%',
				maxValue = 6,
				minWeight = 1,
				maxWeight = 8,
				maxUpgrades = 3,
				upgradeValue1 = 2,
				caustic = true,
			},
			{
				type = 'Hive',
				name = 'Bee Attack',
				sign = '%',
				maxValue = 9,
				minWeight = .1,
				maxWeight = 1,
				maxUpgrades = 3,
				upgradeValue1 = 2,
				bias = 4,
				upgradeValue2 = 3,
				caustic = true,
			},
		},
	},
	["Beekeepers Medal"] = {
		ready = true,
		level = 20,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			otherReq = { 'Bee must be Gifed and be Common, Rare or Epic' },	
		},
	},
	["Charity Bracelet"] = {
		ready = false,
		level = 10,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Basic', 'Hasty', 'Cool', 'Bucko', 'Riley', 'Festive' },
		},
	},
	["Fidget Spinner"] = {
		ready = false,
		level = 12,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Bee must be Common or Rare' },
		},
	},
	["Heroic Helm"] = {
		ready = true,
		level = 15,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Gifted Brave' },
			otherReq = { 'Bee must have a mutation' },
		},
	},
	["Monster Finger Puppet"] = {
		ready = false,
		level = 12,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Rascal', 'Fire', 'Shocked', 'Gummy', 'Vicious' },
			otherReq = { 'Bee must have a mutation' },
		},
	},
	["Pan Lid"] = {
		ready = true,
		level = 9,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Brave', 'Fire', 'Bubble', 'Music', 'Lion', 'Cobalt' },
		},
	},
	["Safety Cone"] = {
		ready = false,
		level = 8,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			otherReq = { 'Bee must be Epic' },
		},
	},
	["Shell Necklace"] = {
		ready = false,
		level = 18,
		color = 'Any',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Basic', 'Rad', 'Exhausted', 'Music', 'Cobalt' },
		},
	},
	["Six Point Shuriken"] = {
		ready = true,
		level = 16,
		color = 'Blue',
		limit = 1,
		desc = ' .',
		require = {
			beeReq = { 'Gifted Ninja' },
			otherReq = { 'Bee must have a mutation' },
		},
	},
}
